import { App as AntApp, ConfigProvider } from 'antd';
import '@testing-library/jest-dom/vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import TemplatesPage from './TemplatesPage';

const api = vi.hoisted(() => ({ fetchChannelAccounts: vi.fn(), fetchSharedTemplates: vi.fn(), fetchMyTemplateChangeRequests: vi.fn(), fetchTemplateChangeRequestsForReview: vi.fn(), fetchSharedTemplate: vi.fn(), fetchTemplateOperations: vi.fn(), createSharedTemplate: vi.fn(), createTemplateChangeRequest: vi.fn(), syncSharedTemplates: vi.fn(), approveTemplateChangeRequest: vi.fn(), rejectTemplateChangeRequest: vi.fn(), retryTemplateChangeRequest: vi.fn(), uploadTemplateMedia: vi.fn(), fetchTemplateMediaUpload: vi.fn(), fetchPublicTemplates: vi.fn() }));
const auth = vi.hoisted(() => ({ isAdmin: false }));
vi.mock('../api/endpoints', () => api);
vi.mock('../hooks/useAuth', () => ({ useAuth: () => auth }));
const template = { id: 'template-1', version: 3, templateCode: 'shipping_notice', name: 'shipping_notice', remark: null, displayName: '发货提醒', language: 'zh_CN', category: 'UTILITY', reviewStatus: 'APPROVED', providerAuditStatus: null, rejectionReason: null, allowSend: true, components: [{ type: 'BODY', headerFormat: null, text: '您好', mediaAssetId: null, buttons: [] }], examples: {}, messageSendTtlSeconds: null, qualityScore: null, providerUpdatedAt: null, lastSyncedAt: null, deletedAt: null };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><ConfigProvider><AntApp><TemplatesPage /></AntApp></ConfigProvider></QueryClientProvider>); }
beforeEach(() => { vi.clearAllMocks(); auth.isAdmin = false; api.fetchChannelAccounts.mockResolvedValue([{ id: 'account-1', channelType: 'chatapp', authStatus: 'active' }]); api.fetchSharedTemplates.mockResolvedValue({ items: [template], total: 1, page: 1, size: 20 }); api.fetchSharedTemplate.mockResolvedValue(template); api.fetchTemplateOperations.mockResolvedValue([]); api.fetchMyTemplateChangeRequests.mockResolvedValue({ items: [], total: 0, page: 1, size: 20 }); api.fetchTemplateChangeRequestsForReview.mockResolvedValue({ items: [], total: 0, page: 1, size: 20 }); });
describe('TemplatesPage shared workspace', () => {
  it('lets ordinary users submit an edit request rather than directly changing the shared template', async () => { const user = userEvent.setup(); api.createTemplateChangeRequest.mockResolvedValue({ mode: 'APPROVAL_REQUIRED', request: { id: 'r1' } }); renderPage(); await screen.findByText('发货提醒'); expect(screen.getByRole('tab', { name: '共享模板' })).toBeVisible(); await user.click(screen.getByRole('button', { name: '编辑 shipping_notice' })); expect(screen.getByRole('button', { name: '提交修改' })).toBeVisible(); await user.click(screen.getByRole('button', { name: '提交修改' })); await waitFor(() => expect(api.createTemplateChangeRequest).toHaveBeenCalledWith('template-1', expect.objectContaining({ expectedVersion: 3, changeType: 'MODIFY' }))); });
  it('requires a shared-impact confirmation before an administrator directly changes send permission', async () => { const user = userEvent.setup(); auth.isAdmin = true; api.createTemplateChangeRequest.mockResolvedValue({ mode: 'DIRECT', request: null }); renderPage(); await screen.findByText('发货提醒'); await user.click(screen.getByRole('button', { name: '暂停发送 shipping_notice' })); const dialog = screen.getByRole('dialog', { name: '暂停模板发送' }); expect(within(dialog).getByText('此变更会影响所有用户。请确认后继续。')).toBeInTheDocument(); await user.click(within(dialog).getByRole('button', { name: '确认影响所有用户' })); await waitFor(() => expect(api.createTemplateChangeRequest).toHaveBeenCalledWith('template-1', expect.objectContaining({ changeType: 'SET_SEND_PERMISSION', allowSend: false }))); });
  it('keeps the shared catalog visible when the current user has no WhatsApp account', async () => { api.fetchChannelAccounts.mockResolvedValue([]); renderPage(); expect(await screen.findByText('发货提醒')).toBeVisible(); expect(screen.getByText('没有可用的 WhatsApp 账号')).toBeVisible(); expect(screen.getByRole('button', { name: /同步模板/ })).toBeDisabled(); });
});
