import { App as AntApp, ConfigProvider } from 'antd';
import '@testing-library/jest-dom/vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import TemplatesPage from './TemplatesPage';

const api = vi.hoisted(() => ({ fetchChannelAccounts: vi.fn(), fetchAdminCams: vi.fn(), fetchSharedTemplates: vi.fn(), fetchMyTemplateChangeRequests: vi.fn(), fetchSharedTemplate: vi.fn(), fetchTemplateOperations: vi.fn(), createSharedTemplate: vi.fn(), createTemplateChangeRequest: vi.fn(), syncSharedTemplates: vi.fn(), uploadTemplateMedia: vi.fn(), fetchTemplateMediaUpload: vi.fn(), fetchPublicTemplates: vi.fn() }));
const auth = vi.hoisted(() => ({ isAdmin: false }));
vi.mock('../api/endpoints', () => api);
vi.mock('../hooks/useAuth', () => ({ useAuth: () => auth }));
const template = { id: 'template-1', version: 3, templateCode: 'shipping_notice', name: 'shipping_notice', remark: null, displayName: '发货提醒', language: 'zh_CN', category: 'UTILITY', reviewStatus: 'APPROVED', providerAuditStatus: null, rejectionReason: null, allowSend: true, components: [{ type: 'BODY', headerFormat: null, text: '您好', mediaAssetId: null, buttons: [] }], examples: {}, messageSendTtlSeconds: null, qualityScore: null, providerUpdatedAt: null, lastSyncedAt: null, deletedAt: null };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={client}><ConfigProvider><AntApp><TemplatesPage /></AntApp></ConfigProvider></QueryClientProvider>); }
beforeEach(() => { vi.clearAllMocks(); auth.isAdmin = false; api.fetchChannelAccounts.mockResolvedValue([{ id: 'account-1', channelType: 'chatapp', authStatus: 'active' }]); api.fetchAdminCams.mockResolvedValue([{ scopeId: 'cams-1', displayName: '小森', custSpaceId: 'cams-9jvb6o87e6m8', status: 'READY' }]); api.fetchSharedTemplates.mockResolvedValue({ items: [template], total: 1, page: 1, size: 20 }); api.fetchSharedTemplate.mockResolvedValue(template); api.fetchTemplateOperations.mockResolvedValue([]); api.fetchMyTemplateChangeRequests.mockResolvedValue({ items: [], total: 0, page: 1, size: 20 }); api.fetchPublicTemplates.mockResolvedValue({ items: [], total: 0, page: 1, size: 20 }); });
describe('TemplatesPage shared workspace', () => {
  it('does not render the redundant shared-template title or subtitle', async () => {
    renderPage();

    await screen.findByText('发货提醒');

    expect(screen.getByRole('heading', { name: 'WhatsApp模板管理' })).toBeVisible();
    expect(screen.queryByRole('heading', { name: '共享模板' })).not.toBeInTheDocument();
    expect(screen.queryByText('系统内所有用户共用同一 WhatsApp 模板目录')).not.toBeInTheDocument();
    expect(screen.getByRole('tab', { name: '共享模板' })).toBeVisible();
    expect(screen.getByRole('tab', { name: '公共模板库' })).toBeVisible();
  });

  it('lets ordinary users submit an edit request rather than directly changing the shared template', async () => { const user = userEvent.setup(); api.createTemplateChangeRequest.mockResolvedValue({ mode: 'APPROVAL_REQUIRED', request: { id: 'r1' } }); renderPage(); await screen.findByText('发货提醒'); expect(screen.getByRole('tab', { name: '共享模板' })).toBeVisible(); await user.click(screen.getByRole('button', { name: '编辑 shipping_notice' })); expect(screen.getByRole('button', { name: '提交修改' })).toBeVisible(); await user.click(screen.getByRole('button', { name: '提交修改' })); await waitFor(() => expect(api.createTemplateChangeRequest).toHaveBeenCalledWith('template-1', expect.objectContaining({ expectedVersion: 3, changeType: 'MODIFY' }), undefined)); });
  it('requires a shared-impact confirmation before an administrator directly changes send permission', async () => { const user = userEvent.setup(); auth.isAdmin = true; api.createTemplateChangeRequest.mockResolvedValue({ mode: 'DIRECT', request: null }); renderPage(); await screen.findByText('发货提醒'); await user.click(screen.getByRole('button', { name: '暂停发送 shipping_notice' })); const dialog = screen.getByRole('dialog', { name: '暂停模板发送' }); expect(within(dialog).getByText('此变更会影响所有用户。请确认后继续。')).toBeInTheDocument(); await user.click(within(dialog).getByRole('button', { name: '确认影响所有用户' })); await waitFor(() => expect(api.createTemplateChangeRequest.mock.calls[0]?.slice(0, 2)).toEqual(['template-1', expect.objectContaining({ changeType: 'SET_SEND_PERMISSION', allowSend: false })])); });
  it('管理员不再看到变更审批标签，且我的申请标签仍可用', async () => { const user = userEvent.setup(); auth.isAdmin = true; renderPage(); await screen.findByText('发货提醒'); expect(screen.queryByRole('tab', { name: '变更审批' })).not.toBeInTheDocument(); const myRequestsTab = screen.getByRole('tab', { name: '我的申请' }); expect(myRequestsTab).toBeVisible(); await user.click(myRequestsTab); expect(await screen.findByText('暂无申请')).toBeVisible(); });
  it('keeps the shared catalog visible when the current user has no WhatsApp account', async () => { api.fetchChannelAccounts.mockResolvedValue([]); renderPage(); expect(await screen.findByText('发货提醒')).toBeVisible(); expect(screen.getByText('没有可用的 WhatsApp 账号')).toBeVisible(); expect(screen.getByRole('button', { name: /同步模板/ })).toBeDisabled(); });
  it('每个 CAMS 空间有自己的模板库，管理员切换空间后按新空间查询', async () => { const user = userEvent.setup(); auth.isAdmin = true; api.fetchAdminCams.mockResolvedValue([{ scopeId: 'cams-1', displayName: '小森', custSpaceId: 'cams-9jvb6o87e6m8', status: 'READY' }, { scopeId: 'cams-2', displayName: '九豆', custSpaceId: 'cams-9dou6dubx2ww', status: 'READY' }]); renderPage(); await screen.findByText('发货提醒'); await waitFor(() => expect(api.fetchSharedTemplates).toHaveBeenCalledWith(expect.objectContaining({ scopeId: 'cams-1' }))); await user.click(screen.getByRole('combobox', { name: '选择 CAMS' })); await user.click(await screen.findByText('九豆（cams-9dou6dubx2ww）')); await waitFor(() => expect(api.fetchSharedTemplates).toHaveBeenCalledWith(expect.objectContaining({ scopeId: 'cams-2' }))); await user.click(screen.getByRole('tab', { name: '公共模板库' })); await waitFor(() => expect(api.fetchPublicTemplates).toHaveBeenLastCalledWith(expect.objectContaining({ language: 'zh_CN' }), 'cams-2')); });
  it('管理员创建和同步模板时带上所选 CAMS 空间', async () => { const user = userEvent.setup(); auth.isAdmin = true; api.fetchAdminCams.mockResolvedValue([{ scopeId: 'cams-1', displayName: '小森', custSpaceId: 'cams-9jvb6o87e6m8', status: 'READY' }, { scopeId: 'cams-2', displayName: '九豆', custSpaceId: 'cams-9dou6dubx2ww', status: 'READY' }]); api.syncSharedTemplates.mockResolvedValue({ fetched: 0, changed: 0 }); api.createSharedTemplate.mockResolvedValue({ id: 'operation-1' }); renderPage(); await screen.findByText('发货提醒'); await user.click(screen.getByRole('combobox', { name: '选择 CAMS' })); await user.click(await screen.findByText('九豆（cams-9dou6dubx2ww）')); await user.click(screen.getByRole('button', { name: /同步模板/ })); await waitFor(() => expect(api.syncSharedTemplates).toHaveBeenCalledWith('cams-2')); await user.click(screen.getByRole('button', { name: '新建模板' })); await user.type(screen.getByLabelText('模板名称'), 'shipping_notice_v2'); const languages = screen.getAllByRole('combobox', { name: '语言' }); fireEvent.mouseDown(languages[languages.length - 1]); await user.click(await screen.findByText('简体中文', { selector: '.ant-select-item-option-content' })); await user.type(screen.getByLabelText('正文'), '您好'); await user.click(screen.getByRole('button', { name: '提交创建' })); await waitFor(() => expect(api.createSharedTemplate).toHaveBeenCalledWith(expect.objectContaining({ name: 'shipping_notice_v2' }), 'cams-2')); });
  it('管理员修改模板和上传素材时带上所选 CAMS 空间', async () => { const user = userEvent.setup(); auth.isAdmin = true; api.fetchAdminCams.mockResolvedValue([{ scopeId: 'cams-1', displayName: '小森', custSpaceId: 'cams-9jvb6o87e6m8', status: 'READY' }, { scopeId: 'cams-2', displayName: '九豆', custSpaceId: 'cams-9dou6dubx2ww', status: 'READY' }]); api.createTemplateChangeRequest.mockResolvedValue({ mode: 'APPROVAL_REQUIRED', request: { id: 'r1' } }); api.uploadTemplateMedia.mockResolvedValue({ id: 'asset-1', clientRequestId: 'upload-1', format: 'IMAGE', contentType: 'image/png', sizeBytes: 3, sha256: 'a', providerUrl: null, assetStatus: 'UPLOADED', errorCode: null, errorMessage: null, traceId: 't' }); renderPage(); await screen.findByText('发货提醒'); await user.click(screen.getByRole('combobox', { name: '选择 CAMS' })); await user.click(await screen.findByText('九豆（cams-9dou6dubx2ww）')); await user.click(screen.getByRole('button', { name: '编辑 shipping_notice' })); await user.click(screen.getByRole('button', { name: '提交修改' })); await waitFor(() => expect(api.createTemplateChangeRequest).toHaveBeenCalledWith('template-1', expect.objectContaining({ changeType: 'MODIFY' }), 'cams-2')); await user.click(screen.getByRole('button', { name: '编辑 shipping_notice' })); const headerTypes = screen.getAllByRole('combobox', { name: 'Header 类型' }); fireEvent.mouseDown(headerTypes[headerTypes.length - 1]); await user.click(await screen.findByText('图片', { selector: '.ant-select-item-option-content' })); fireEvent.change(screen.getByLabelText('Header 素材'), { target: { files: [new File(['x'], 'header.png', { type: 'image/png' })] } }); await waitFor(() => expect(api.uploadTemplateMedia).toHaveBeenCalledWith('IMAGE', expect.any(File), expect.any(String), expect.any(AbortSignal), undefined, 'cams-2')); });
  it('普通用户看不到空间选择器，也不向服务端传 scopeId', async () => { const user = userEvent.setup(); renderPage(); await screen.findByText('发货提醒'); expect(screen.queryByRole('combobox', { name: '选择 CAMS' })).not.toBeInTheDocument(); expect(api.fetchSharedTemplates.mock.calls[0][0].scopeId).toBeUndefined(); await user.click(screen.getByRole('tab', { name: '公共模板库' })); await waitFor(() => expect(api.fetchPublicTemplates).toHaveBeenLastCalledWith(expect.objectContaining({ language: 'zh_CN' }), undefined)); });
});
