package com.crmforlogistics.messagecenter.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.bind.DefaultValue;

@ConfigurationProperties(prefix = "app")
public record AppConfig(
        @DefaultValue("8099") int port,
        @DefaultValue("${user.dir}/data") String dataDir,
        String webBindAddress,
        String databaseUrl,
        String databaseUser,
        String databasePasswordFile,
        boolean localDevMode,
        String custSpaceId,
        String chatappFrom,
        String chatappTo,
        String chatappChannelType,
        @DefaultValue("true") boolean chatappSyncEnabled,
        @DefaultValue("true") boolean chatappTemplateReconcileEnabled,
        @DefaultValue("300000") long chatappTemplateReconcileIntervalMs,
        String aliyunAccessKeyId,
        String aliyunAccessKeySecret,
        String camsRegion,
        String camsEndpoint,
        String smtpHost,
        String smtpPort,
        String smtpUser,
        String smtpPasswordFile,
        String smtpPassword,
        @DefaultValue("true") boolean smtpSsl,
        @DefaultValue("false") boolean smtpStartTls,
        @DefaultValue("true") boolean smtpResolveIpv4,
        String smtpLocalhost,
        String mailFrom,
        String mailFromName,
        String imapHost,
        String imapPort,
        String imapUser,
        String imapPasswordFile,
        String imapPassword,
        @DefaultValue("true") boolean imapSsl,
        @DefaultValue("10") int receiveLimit,
        @DefaultValue("auto") String mailProvider,
        @DefaultValue("true") boolean imap139UseOpenssl,
        @DefaultValue("/usr/bin/openssl") String opensslBin,
        @DefaultValue("false") boolean emailSyncEnabled,
        @DefaultValue("INBOX") String inboxFolder,
        @DefaultValue("Sent") String sentFolder,
        // WeCom
        String wecomSuiteId,
        String wecomSuiteSecret,
        String wecomToken,
        String wecomEncodingAesKey,
        @DefaultValue("") String wecomCallbackReceiveId,
        @DefaultValue("https://qyapi.weixin.qq.com") String wecomApiBaseUrl,
        @DefaultValue("10") int wecomApiTimeoutSeconds,
        @DefaultValue("300") int wecomTokenRefreshSkewSeconds,
        @DefaultValue("") String wecomLoginSuiteId,
        @DefaultValue("") String wecomLoginSuiteSecret,
        @DefaultValue("") String wecomCorpId,
        @DefaultValue("") String wecomAgentId,
        @DefaultValue("") String wecomSecret,
        @DefaultValue("") String wecomLoginAuthCorpId,
        @DefaultValue("http://localhost:8099/") String wecomLoginRedirectUri,
        @DefaultValue("300") int wecomLoginAttemptTtlSeconds,
        @DefaultValue("256") int wecomLoginMaxPending,
        @DefaultValue("20") int wecomLoginAttemptRateLimitPerMinute,
        @DefaultValue("") String wecomAllowedJsapiOrigins,
        @DefaultValue("28800") int wecomViewerAuthTtlSeconds,
        @DefaultValue("300") int wecomViewerSessionTtlSeconds,
        @DefaultValue("15") int wecomViewerMaxMessages,
        @DefaultValue("10") int wecomViewerSessionRateLimit,
        @DefaultValue("64") int wecomAuthorizationQueueCapacity,
        @DefaultValue("") String wecomChatDataProgramId,
        @DefaultValue("") String wecomChatDataAbilityId,
        @DefaultValue("false") boolean wecomChatDataDiagnostics,
        @DefaultValue("") String wecomChatDataPrivateKeyFile,
        @DefaultValue("1") int wecomChatDataPublicKeyVersion,
        @DefaultValue("false") boolean wecomChatDataPublicKeyAutoRegister,
        @DefaultValue("200") int wecomChatDataSyncLimit,
        @DefaultValue("5") int wecomChatDataSyncMaxPages,
        @DefaultValue("15") int wecomChatDataSyncTimeoutSeconds,
        @DefaultValue("true") boolean wecomChatDataAutoSyncEnabled,
        @DefaultValue("60") int wecomChatDataAutoSyncIntervalSeconds,
        @DefaultValue("5000") int wecomChatDataStoreMaxMessages,
        @DefaultValue("8388608") long wecomChatDataStoreMaxBytes,
        @DefaultValue("false") boolean wecomDailySummaryEnabled,
        @DefaultValue("conversation_daily_summary") String wecomDailySummaryAbilityId,
        @DefaultValue("0") int wecomDailySummaryHour,
        @DefaultValue("5") int wecomDailySummaryMinute,
        @DefaultValue("32") int wecomDailySummaryMaxBatches,
        @DefaultValue("20") int wecomDailySummaryMaxTransientAttempts,
        @DefaultValue("900") int wecomDailySummaryMaxBackoffSeconds,
        @DefaultValue("30") int wecomDailySummaryPollInitialSeconds,
        @DefaultValue("24") int wecomDailySummaryMaxWaitHours,
        @DefaultValue("fixture") String localWeComDataSource,
        @DefaultValue("local-wecom-source.jsonl") String localWeComDataFile,
        @DefaultValue("") String chatappWebhookSecret,
        @DefaultValue("300") int chatappWebhookMaxSkewSeconds
) {}
