spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/message_center
    username: message_center
    password: ${postgres_password}
  flyway:
    enabled: true
    locations: classpath:db/migration

postgres_password: placeholder

minio:
  endpoint: http://localhost:9000
  access-key: ${MINIO_ACCESS_KEY:}
  secret-key: ${MINIO_SECRET_KEY:}
  bucket: message-center
